{
  "name": "invalidbreak",
  "description": "throws the exception : break has been invoked outside of a loop",
  "labels": ["exception"],
  "signature": {
    "input": [],
    "output": [],
    "exceptions": ["invalidbreak"]
  },
  "samples": []
}
